server:
  port: 9090
  
keycloak:
  realm: oauth2-test
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: read-user-service
  use-resource-role-mappings: false
  bearer-only: true